title: Emotion Transfer Based on Global Style Tokens and Adversarial Training
description: "Pengfei Wu, Junjie Pan, Junhui Zhang, Chenchang Xu, Lin Wu, Xiang Yin, Zejun Ma<br><br>ByteDance AI Lab"
theme: jekyll-theme-cayman