# title: Emotion Transfer Based on Global Style Tokens and Adversarial Training
# description: "Pengfei Wu, Junjie Pan, Chenchang Xu, Junhui Zhang, Lin Wu, Xiang Yin, Zejun Ma<br><br>ByteDance AI Lab"
# theme: jekyll-theme-cayman